import { Type } from "@sinclair/typebox";

export const GithubParams = Type.Object({
	action: Type.Optional(
		Type.Union(
			[
				Type.Literal("format"),
				Type.Literal("list_images"),
				Type.Literal("download_image"),
				Type.Literal("list_changes"),
				Type.Literal("get_change"),
				Type.Literal("list_issues"),
				Type.Literal("list_prs"),
				Type.Literal("pr_overview"),
				Type.Literal("list_pr_commits"),
				Type.Literal("get_pr_commit"),
				Type.Literal("list_review_comments"),
				Type.Literal("list_pr_checks"),
				Type.Literal("list_participants"),
				Type.Literal("read_file"),
				Type.Literal("list_directory"),
				Type.Literal("search_code"),
				Type.Literal("glob_files"),
				Type.Literal("search_commits"),
			],
			{
				description:
					"Action: format thread markdown; list_issues/list_prs; list_images/download_image; or list_changes/get_change for PR file diffs",
			},
		),
	),
	id: Type.Optional(Type.Integer({ minimum: 1, description: "GitHub thread ID (issue/PR/discussion number)" })),
	entity: Type.Optional(Type.Union([Type.Literal("issue"), Type.Literal("pr"), Type.Literal("discussion")])),
	owner: Type.Optional(Type.String({ description: "GitHub repository owner/org (optional; auto-detected from git origin)" })),
	repo: Type.Optional(Type.String({ description: "GitHub repository name (optional; auto-detected from git origin)" })),
	number: Type.Optional(Type.Integer({ minimum: 1, description: "Deprecated alias for id" })),
	page: Type.Optional(Type.Integer({ minimum: 1, description: "Pagination page (default 1)" })),
	perPage: Type.Optional(Type.Integer({ minimum: 1, maximum: 100, description: "Items per page (default 20)" })),
	imageId: Type.Optional(Type.Integer({ minimum: 1, description: "Image ID (for download_image)" })),
	changeId: Type.Optional(Type.Integer({ minimum: 1, description: "Change ID (for get_change)" })),
	patchId: Type.Optional(Type.Integer({ minimum: 1, description: "Alias for changeId" })),
	codeId: Type.Optional(Type.Integer({ minimum: 1, description: "Alias for changeId" })),
	tmpDir: Type.Optional(Type.String({ description: "Download directory for images (default /tmp)" })),
	path: Type.Optional(Type.String({ description: "File path filter or file path for file-focused actions" })),
	ref: Type.Optional(Type.String({ description: "Git ref (branch/tag/SHA) for ref-aware actions" })),
	startLine: Type.Optional(Type.Integer({ minimum: 1, description: "Start line for file output (1-indexed)" })),
	endLine: Type.Optional(Type.Integer({ minimum: 1, description: "End line for file output (1-indexed)" })),
	commitSha: Type.Optional(Type.String({ description: "PR commit SHA for action=get_pr_commit" })),
	includeFiles: Type.Optional(Type.Boolean({ description: "Include changed files in action=pr_overview (default true)" })),
	includeReviews: Type.Optional(Type.Boolean({ description: "Include review summary in action=pr_overview (default true)" })),
	includeChecks: Type.Optional(Type.Boolean({ description: "Include checks summary in action=pr_overview (default true)" })),
	author: Type.Optional(Type.String({ description: "Filter by author login" })),
	kind: Type.Optional(Type.String({ description: "Filter by thread item kind" })),
	since: Type.Optional(Type.String({ description: "ISO date/time lower bound filter" })),
	until: Type.Optional(Type.String({ description: "ISO date/time upper bound filter" })),
	contains: Type.Optional(Type.String({ description: "Case-insensitive body substring filter" })),
	query: Type.Optional(Type.String({ description: "Search query for action=search_code/search_commits" })),
	filePattern: Type.Optional(Type.String({ description: "Glob pattern for action=glob_files" })),
	limit: Type.Optional(Type.Integer({ minimum: 1, description: "Maximum results for list/search actions" })),
	offset: Type.Optional(Type.Integer({ minimum: 0, description: "Offset for paginated list/search actions" })),
});
